# fly.toml app configuration file generated for listing on 2023-09-02T13:15:29+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "listing"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
